const UI_LOADING_STATES = {
  INIT: "INIT",
  LOADING: "LOADING",
  ERROR: "ERROR",
};

const APP_PATH = {
  EMPLOYEE_HOME: "EMP_HOME",
  ADD_EMPLOYEE: "ADD_EMP",
  ROLE_HOME: "ROLE_HOME",
  ADD_ROLE: "ADD_ROLE",
  ORG_HOME: "ORG_HOME",
  ADD_ORG: "ADD_ORG",
  DEPT_HOME: "DEPT_HOME",
  ADD_DEPT: "ADD_DEPT"
};

export { UI_LOADING_STATES, APP_PATH };
