/**
 * 
 * 
 * This file contains the constants  
 */
const AUTH = 'yLFSNX01hx09YqjIaJujSuZWhu7S2EwytjnLfl0OZ5Q';
const APP_PATH = {
  EMPLOYEE_HOME: "EMP_HOME",
  ADD_EMPLOYEE: "ADD_EMP",
  VIEW_EMPLOYEE: "VIEW_EMP",
  ROLE_HOME: "ROLE_HOME",
  ADD_ROLE: "ADD_ROLE",
  VIEW_ROLE: "VIEW_ROLE",
  ORG_HOME: "ORG_HOME",
  ADD_ORG: "ADD_ORG",
  VIEW_ORG: "VIEW_ORG",
  DEPT_HOME: "DEPT_HOME",
  ADD_DEPT: "ADD_DEPT",
  VIEW_LEAVE: "VIEW_LEAVE",
  ADD_LEAVE: "ADD_LEAVE",
  VIEW_DEPT: "VIEW_DEPT",
  PAYROLL_HOME: "PAYROLL_HOME"
};

export { APP_PATH, AUTH};
